// @generated drizzle-zero signature:sha256:1569bea8babdd19ae007d6b08677c6ab6f03b8bd98d270e44648bfbb3ea792e2
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const agentWorkflowRunsTable = {
  name: "agentWorkflowRuns",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    flueRunId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "flue_run_id",
    },
    workflowName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "workflow_name",
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    requestedByUserId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "requested_by_user_id",
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    error: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    finishedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "finished_at",
    },
  },
  primaryKey: ["id"],
  serverName: "agent_workflow_runs",
} as const;
const bankAccountsTable = {
  name: "bankAccounts",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    bankConnectionId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_connection_id",
    },
    provider: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    providerInstitutionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_institution_id",
    },
    providerRequisitionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_requisition_id",
    },
    providerAccountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_account_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    iban: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    currency: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    syncStatus: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "sync_status",
    },
    syncError: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "sync_error",
    },
    syncStartedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "sync_started_at",
    },
    lastSyncedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_synced_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "bank_accounts",
} as const;
const bankConnectionsTable = {
  name: "bankConnections",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    provider: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    providerInstitutionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_institution_id",
    },
    providerRequisitionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_requisition_id",
    },
    reference: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "bank_connections",
} as const;
const bankTransactionsTable = {
  name: "bankTransactions",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    bankAccountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "bank_account_id",
    },
    providerTransactionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_transaction_id",
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    bookingDate: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "booking_date",
    },
    valueDate: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "value_date",
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    currency: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    counterpartyName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "counterparty_name",
    },
    aiConfidence: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ai_confidence",
    },
    aiProcessingStartedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ai_processing_started_at",
    },
    aiReasoning: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ai_reasoning",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "bank_transactions",
} as const;
const ledgerAccountGroupsTable = {
  name: "ledgerAccountGroups",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    systemKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "system_key",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    sortOrder: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "ledger_account_groups",
} as const;
const ledgerAccountsTable = {
  name: "ledgerAccounts",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    groupId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "group_id",
    },
    linkedBankAccountId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "linked_bank_account_id",
    },
    systemKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "system_key",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    normalBalance: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "normal_balance",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    sortOrder: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "ledger_accounts",
} as const;
const ledgerPostingsTable = {
  name: "ledgerPostings",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    ledgerTransactionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "ledger_transaction_id",
    },
    accountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_id",
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    currency: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    bankTransactionId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "bank_transaction_id",
    },
    sortOrder: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "ledger_postings",
} as const;
const ledgerTransactionsTable = {
  name: "ledgerTransactions",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    source: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    categorizedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "categorized_by",
    },
    userConfirmedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "user_confirmed_at",
    },
    userConfirmedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "user_confirmed_by",
    },
    date: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "ledger_transactions",
} as const;
const teamMembersTable = {
  name: "teamMembers",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "team_members",
} as const;
const teamsTable = {
  name: "teams",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    personalOwnerUserId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "personal_owner_user_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const agentWorkflowRunsRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "teams",
      cardinality: "one",
    },
  ],
} as const;
const bankAccountsRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "teams",
      cardinality: "one",
    },
  ],
  connection: [
    {
      sourceField: ["bankConnectionId"],
      destField: ["id"],
      destSchema: "bankConnections",
      cardinality: "one",
    },
  ],
  transactions: [
    {
      sourceField: ["id"],
      destField: ["bankAccountId"],
      destSchema: "bankTransactions",
      cardinality: "many",
    },
  ],
  ledgerAccount: [
    {
      sourceField: ["id"],
      destField: ["linkedBankAccountId"],
      destSchema: "ledgerAccounts",
      cardinality: "one",
    },
  ],
} as const;
const bankConnectionsRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "teams",
      cardinality: "one",
    },
  ],
  bankAccounts: [
    {
      sourceField: ["id"],
      destField: ["bankConnectionId"],
      destSchema: "bankAccounts",
      cardinality: "many",
    },
  ],
} as const;
const bankTransactionsRelationships = {
  bankAccount: [
    {
      sourceField: ["bankAccountId"],
      destField: ["id"],
      destSchema: "bankAccounts",
      cardinality: "one",
    },
  ],
  posting: [
    {
      sourceField: ["id"],
      destField: ["bankTransactionId"],
      destSchema: "ledgerPostings",
      cardinality: "one",
    },
  ],
} as const;
const ledgerAccountGroupsRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "teams",
      cardinality: "one",
    },
  ],
  accounts: [
    {
      sourceField: ["id"],
      destField: ["groupId"],
      destSchema: "ledgerAccounts",
      cardinality: "many",
    },
  ],
} as const;
const ledgerAccountsRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "teams",
      cardinality: "one",
    },
  ],
  group: [
    {
      sourceField: ["groupId"],
      destField: ["id"],
      destSchema: "ledgerAccountGroups",
      cardinality: "one",
    },
  ],
  linkedBankAccount: [
    {
      sourceField: ["linkedBankAccountId"],
      destField: ["id"],
      destSchema: "bankAccounts",
      cardinality: "one",
    },
  ],
  postings: [
    {
      sourceField: ["id"],
      destField: ["accountId"],
      destSchema: "ledgerPostings",
      cardinality: "many",
    },
  ],
} as const;
const ledgerPostingsRelationships = {
  ledgerTransaction: [
    {
      sourceField: ["ledgerTransactionId"],
      destField: ["id"],
      destSchema: "ledgerTransactions",
      cardinality: "one",
    },
  ],
  account: [
    {
      sourceField: ["accountId"],
      destField: ["id"],
      destSchema: "ledgerAccounts",
      cardinality: "one",
    },
  ],
  bankTransaction: [
    {
      sourceField: ["bankTransactionId"],
      destField: ["id"],
      destSchema: "bankTransactions",
      cardinality: "one",
    },
  ],
} as const;
const ledgerTransactionsRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "teams",
      cardinality: "one",
    },
  ],
  postings: [
    {
      sourceField: ["id"],
      destField: ["ledgerTransactionId"],
      destSchema: "ledgerPostings",
      cardinality: "many",
    },
  ],
} as const;
const teamMembersRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "teams",
      cardinality: "one",
    },
  ],
} as const;
const teamsRelationships = {
  members: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "teamMembers",
      cardinality: "many",
    },
  ],
  agentWorkflowRuns: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "agentWorkflowRuns",
      cardinality: "many",
    },
  ],
  bankConnections: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "bankConnections",
      cardinality: "many",
    },
  ],
  bankAccounts: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "bankAccounts",
      cardinality: "many",
    },
  ],
  ledgerAccountGroups: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "ledgerAccountGroups",
      cardinality: "many",
    },
  ],
  ledgerAccounts: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "ledgerAccounts",
      cardinality: "many",
    },
  ],
  ledgerTransactions: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "ledgerTransactions",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    agentWorkflowRuns: agentWorkflowRunsTable,
    bankAccounts: bankAccountsTable,
    bankConnections: bankConnectionsTable,
    bankTransactions: bankTransactionsTable,
    ledgerAccountGroups: ledgerAccountGroupsTable,
    ledgerAccounts: ledgerAccountsTable,
    ledgerPostings: ledgerPostingsTable,
    ledgerTransactions: ledgerTransactionsTable,
    teamMembers: teamMembersTable,
    teams: teamsTable,
  },
  relationships: {
    agentWorkflowRuns: agentWorkflowRunsRelationships,
    bankAccounts: bankAccountsRelationships,
    bankConnections: bankConnectionsRelationships,
    bankTransactions: bankTransactionsRelationships,
    ledgerAccountGroups: ledgerAccountGroupsRelationships,
    ledgerAccounts: ledgerAccountsRelationships,
    ledgerPostings: ledgerPostingsRelationships,
    ledgerTransactions: ledgerTransactionsRelationships,
    teamMembers: teamMembersRelationships,
    teams: teamsRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "agentWorkflowRuns" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AgentWorkflowRun = Row<
  (typeof schema)["tables"]["agentWorkflowRuns"]
>;
/**
 * Represents a row from the "bankAccounts" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BankAccount = Row<(typeof schema)["tables"]["bankAccounts"]>;
/**
 * Represents a row from the "bankConnections" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BankConnection = Row<(typeof schema)["tables"]["bankConnections"]>;
/**
 * Represents a row from the "bankTransactions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BankTransaction = Row<
  (typeof schema)["tables"]["bankTransactions"]
>;
/**
 * Represents a row from the "ledgerAccountGroups" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type LedgerAccountGroup = Row<
  (typeof schema)["tables"]["ledgerAccountGroups"]
>;
/**
 * Represents a row from the "ledgerAccounts" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type LedgerAccount = Row<(typeof schema)["tables"]["ledgerAccounts"]>;
/**
 * Represents a row from the "ledgerPostings" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type LedgerPosting = Row<(typeof schema)["tables"]["ledgerPostings"]>;
/**
 * Represents a row from the "ledgerTransactions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type LedgerTransaction = Row<
  (typeof schema)["tables"]["ledgerTransactions"]
>;
/**
 * Represents a row from the "teamMembers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TeamMember = Row<(typeof schema)["tables"]["teamMembers"]>;
/**
 * Represents a row from the "teams" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Team = Row<(typeof schema)["tables"]["teams"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
