import {string as zeroString} from '@rocicorp/zero'
import {drizzleZeroConfig} from 'drizzle-zero'
import * as drizzleSchema from './src/db/schema'

export default drizzleZeroConfig(drizzleSchema, {
  tables: {
    user: false,
    session: false,
    account: false,
    verification: false,
    teams: {
      id: true,
      name: true,
      personalOwnerUserId: true,
      createdAt: true,
      updatedAt: true,
    },
    teamMembers: {
      id: true,
      teamId: true,
      userId: true,
      role: true,
      createdAt: true,
      updatedAt: true,
    },
    bankConnections: {
      id: true,
      teamId: true,
      provider: true,
      providerInstitutionId: true,
      providerRequisitionId: true,
      reference: true,
      status: true,
      createdAt: true,
      updatedAt: true,
    },
    bankAccounts: {
      id: true,
      teamId: true,
      bankConnectionId: true,
      provider: true,
      providerInstitutionId: true,
      providerRequisitionId: true,
      providerAccountId: true,
      name: true,
      iban: true,
      currency: true,
      status: true,
      syncStatus: zeroString().from('sync_status'),
      syncError: true,
      syncStartedAt: true,
      lastSyncedAt: true,
      createdAt: true,
      updatedAt: true,
    },
    bankTransactions: {
      id: true,
      bankAccountId: true,
      providerTransactionId: true,
      status: true,
      bookingDate: true,
      valueDate: true,
      amount: true,
      currency: true,
      description: true,
      counterpartyName: true,
      raw: true,
      createdAt: true,
      updatedAt: true,
    },
    ledgerAccountGroups: {
      id: true,
      teamId: true,
      name: true,
      sortOrder: true,
      createdAt: true,
      updatedAt: true,
    },
    ledgerAccounts: {
      id: true,
      teamId: true,
      groupId: true,
      linkedBankAccountId: true,
      systemKey: true,
      type: true,
      normalBalance: true,
      name: true,
      description: true,
      status: true,
      sortOrder: true,
      createdAt: true,
      updatedAt: true,
    },
    ledgerTransactions: {
      id: true,
      teamId: true,
      bankTransactionId: true,
      source: true,
      status: true,
      aiConfidence: true,
      aiProcessingStartedAt: true,
      categorizedBy: true,
      userConfirmedAt: true,
      userConfirmedBy: true,
      aiReasoning: true,
      date: true,
      description: true,
      createdAt: true,
      updatedAt: true,
    },
    ledgerTransactionMovements: {
      id: true,
      ledgerTransactionId: true,
      debitAccountId: true,
      creditAccountId: true,
      amount: true,
      currency: true,
      sortOrder: true,
      createdAt: true,
      updatedAt: true,
    },
  },
})
