/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedLedgerRouteImport } from './routes/_protected/ledger'
import { Route as ProtectedAppRouteImport } from './routes/_protected/app'
import { Route as ApiZeroQueryRouteImport } from './routes/api/zero/query'
import { Route as ApiZeroMutateRouteImport } from './routes/api/zero/mutate'
import { Route as ApiGocardlessCallbackRouteImport } from './routes/api/gocardless/callback'
import { Route as ApiFlueSplatRouteImport } from './routes/api/flue/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAppTransactionsRouteImport } from './routes/_protected/app/transactions'
import { Route as ProtectedAppCategoriesRouteImport } from './routes/_protected/app/categories'
import { Route as ProtectedAppBanksRouteImport } from './routes/_protected/app/banks'
import { Route as ProtectedAppBanksConnectRouteImport } from './routes/_protected/app/banks.connect'
import { Route as ProtectedAppBankAccountsBankAccountIdRouteImport } from './routes/_protected/app/bank-accounts/$bankAccountId'
import { Route as ProtectedAppAccountsAccountIdRouteImport } from './routes/_protected/app/accounts/$accountId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLedgerRoute = ProtectedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppRoute = ProtectedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiZeroQueryRoute = ApiZeroQueryRouteImport.update({
  id: '/api/zero/query',
  path: '/api/zero/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroMutateRoute = ApiZeroMutateRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGocardlessCallbackRoute = ApiGocardlessCallbackRouteImport.update({
  id: '/api/gocardless/callback',
  path: '/api/gocardless/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlueSplatRoute = ApiFlueSplatRouteImport.update({
  id: '/api/flue/$',
  path: '/api/flue/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppTransactionsRoute =
  ProtectedAppTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => ProtectedAppRoute,
  } as any)
const ProtectedAppCategoriesRoute = ProtectedAppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ProtectedAppRoute,
} as any)
const ProtectedAppBanksRoute = ProtectedAppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => ProtectedAppRoute,
} as any)
const ProtectedAppBanksConnectRoute =
  ProtectedAppBanksConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => ProtectedAppBanksRoute,
  } as any)
const ProtectedAppBankAccountsBankAccountIdRoute =
  ProtectedAppBankAccountsBankAccountIdRouteImport.update({
    id: '/bank-accounts/$bankAccountId',
    path: '/bank-accounts/$bankAccountId',
    getParentRoute: () => ProtectedAppRoute,
  } as any)
const ProtectedAppAccountsAccountIdRoute =
  ProtectedAppAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => ProtectedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof ProtectedAppRouteWithChildren
  '/ledger': typeof ProtectedLedgerRoute
  '/app/banks': typeof ProtectedAppBanksRouteWithChildren
  '/app/categories': typeof ProtectedAppCategoriesRoute
  '/app/transactions': typeof ProtectedAppTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/flue/$': typeof ApiFlueSplatRoute
  '/api/gocardless/callback': typeof ApiGocardlessCallbackRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/app/accounts/$accountId': typeof ProtectedAppAccountsAccountIdRoute
  '/app/bank-accounts/$bankAccountId': typeof ProtectedAppBankAccountsBankAccountIdRoute
  '/app/banks/connect': typeof ProtectedAppBanksConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof ProtectedAppRouteWithChildren
  '/ledger': typeof ProtectedLedgerRoute
  '/app/banks': typeof ProtectedAppBanksRouteWithChildren
  '/app/categories': typeof ProtectedAppCategoriesRoute
  '/app/transactions': typeof ProtectedAppTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/flue/$': typeof ApiFlueSplatRoute
  '/api/gocardless/callback': typeof ApiGocardlessCallbackRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/app/accounts/$accountId': typeof ProtectedAppAccountsAccountIdRoute
  '/app/bank-accounts/$bankAccountId': typeof ProtectedAppBankAccountsBankAccountIdRoute
  '/app/banks/connect': typeof ProtectedAppBanksConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/app': typeof ProtectedAppRouteWithChildren
  '/_protected/ledger': typeof ProtectedLedgerRoute
  '/_protected/app/banks': typeof ProtectedAppBanksRouteWithChildren
  '/_protected/app/categories': typeof ProtectedAppCategoriesRoute
  '/_protected/app/transactions': typeof ProtectedAppTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/flue/$': typeof ApiFlueSplatRoute
  '/api/gocardless/callback': typeof ApiGocardlessCallbackRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/_protected/app/accounts/$accountId': typeof ProtectedAppAccountsAccountIdRoute
  '/_protected/app/bank-accounts/$bankAccountId': typeof ProtectedAppBankAccountsBankAccountIdRoute
  '/_protected/app/banks/connect': typeof ProtectedAppBanksConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/ledger'
    | '/app/banks'
    | '/app/categories'
    | '/app/transactions'
    | '/api/auth/$'
    | '/api/flue/$'
    | '/api/gocardless/callback'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/app/accounts/$accountId'
    | '/app/bank-accounts/$bankAccountId'
    | '/app/banks/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/ledger'
    | '/app/banks'
    | '/app/categories'
    | '/app/transactions'
    | '/api/auth/$'
    | '/api/flue/$'
    | '/api/gocardless/callback'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/app/accounts/$accountId'
    | '/app/bank-accounts/$bankAccountId'
    | '/app/banks/connect'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/app'
    | '/_protected/ledger'
    | '/_protected/app/banks'
    | '/_protected/app/categories'
    | '/_protected/app/transactions'
    | '/api/auth/$'
    | '/api/flue/$'
    | '/api/gocardless/callback'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/_protected/app/accounts/$accountId'
    | '/_protected/app/bank-accounts/$bankAccountId'
    | '/_protected/app/banks/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFlueSplatRoute: typeof ApiFlueSplatRoute
  ApiGocardlessCallbackRoute: typeof ApiGocardlessCallbackRoute
  ApiZeroMutateRoute: typeof ApiZeroMutateRoute
  ApiZeroQueryRoute: typeof ApiZeroQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/ledger': {
      id: '/_protected/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof ProtectedLedgerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app': {
      id: '/_protected/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/zero/query': {
      id: '/api/zero/query'
      path: '/api/zero/query'
      fullPath: '/api/zero/query'
      preLoaderRoute: typeof ApiZeroQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gocardless/callback': {
      id: '/api/gocardless/callback'
      path: '/api/gocardless/callback'
      fullPath: '/api/gocardless/callback'
      preLoaderRoute: typeof ApiGocardlessCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flue/$': {
      id: '/api/flue/$'
      path: '/api/flue/$'
      fullPath: '/api/flue/$'
      preLoaderRoute: typeof ApiFlueSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/app/transactions': {
      id: '/_protected/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof ProtectedAppTransactionsRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
    '/_protected/app/categories': {
      id: '/_protected/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof ProtectedAppCategoriesRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
    '/_protected/app/banks': {
      id: '/_protected/app/banks'
      path: '/banks'
      fullPath: '/app/banks'
      preLoaderRoute: typeof ProtectedAppBanksRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
    '/_protected/app/banks/connect': {
      id: '/_protected/app/banks/connect'
      path: '/connect'
      fullPath: '/app/banks/connect'
      preLoaderRoute: typeof ProtectedAppBanksConnectRouteImport
      parentRoute: typeof ProtectedAppBanksRoute
    }
    '/_protected/app/bank-accounts/$bankAccountId': {
      id: '/_protected/app/bank-accounts/$bankAccountId'
      path: '/bank-accounts/$bankAccountId'
      fullPath: '/app/bank-accounts/$bankAccountId'
      preLoaderRoute: typeof ProtectedAppBankAccountsBankAccountIdRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
    '/_protected/app/accounts/$accountId': {
      id: '/_protected/app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/app/accounts/$accountId'
      preLoaderRoute: typeof ProtectedAppAccountsAccountIdRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
  }
}

interface ProtectedAppBanksRouteChildren {
  ProtectedAppBanksConnectRoute: typeof ProtectedAppBanksConnectRoute
}

const ProtectedAppBanksRouteChildren: ProtectedAppBanksRouteChildren = {
  ProtectedAppBanksConnectRoute: ProtectedAppBanksConnectRoute,
}

const ProtectedAppBanksRouteWithChildren =
  ProtectedAppBanksRoute._addFileChildren(ProtectedAppBanksRouteChildren)

interface ProtectedAppRouteChildren {
  ProtectedAppBanksRoute: typeof ProtectedAppBanksRouteWithChildren
  ProtectedAppCategoriesRoute: typeof ProtectedAppCategoriesRoute
  ProtectedAppTransactionsRoute: typeof ProtectedAppTransactionsRoute
  ProtectedAppAccountsAccountIdRoute: typeof ProtectedAppAccountsAccountIdRoute
  ProtectedAppBankAccountsBankAccountIdRoute: typeof ProtectedAppBankAccountsBankAccountIdRoute
}

const ProtectedAppRouteChildren: ProtectedAppRouteChildren = {
  ProtectedAppBanksRoute: ProtectedAppBanksRouteWithChildren,
  ProtectedAppCategoriesRoute: ProtectedAppCategoriesRoute,
  ProtectedAppTransactionsRoute: ProtectedAppTransactionsRoute,
  ProtectedAppAccountsAccountIdRoute: ProtectedAppAccountsAccountIdRoute,
  ProtectedAppBankAccountsBankAccountIdRoute:
    ProtectedAppBankAccountsBankAccountIdRoute,
}

const ProtectedAppRouteWithChildren = ProtectedAppRoute._addFileChildren(
  ProtectedAppRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAppRoute: typeof ProtectedAppRouteWithChildren
  ProtectedLedgerRoute: typeof ProtectedLedgerRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppRoute: ProtectedAppRouteWithChildren,
  ProtectedLedgerRoute: ProtectedLedgerRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFlueSplatRoute: ApiFlueSplatRoute,
  ApiGocardlessCallbackRoute: ApiGocardlessCallbackRoute,
  ApiZeroMutateRoute: ApiZeroMutateRoute,
  ApiZeroQueryRoute: ApiZeroQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
